### ISSUE TITLE
오픈소스를 읽는 방법

### ISSUE THREAD

**Issue by choisungwook** [GwonsooLee/Podcast#10]

**Comment by GwonsooLee** [comment]
오픈소스는 생각보다 코드가 방대하기 때문에, 모든 코드를 전부 살펴보기 어려운 경우가 많습니다. 시간이 많다면 모르겠지만, 시간이 넉넉하지 못하다면, 빠르게 원하는 코드 부분만 찾을 수 있는 자신만의 방법을 찾는 것도 좋아보입니다.

저는 오픈소스에서 로직을 찾을 때 다음과 같은 방식으로 찾습니다.

1. 먼저 오픈소스에서 제공해준 로그 문구를 검색해서 해당 문구를 가지고 검색합니다. 이때 Formatting 될 것 같은 문구는 빼고 찾습니다.
2. 로그로 찾지 못하면, claude나 chatgpt에게 함수의 이름을 물어보고 찾습니다.
3. 특정 함수를 찾게 되면, 함수를 사용하는 곳을 역추적해서 전체 흐름을 판단합니다.

**Comment by choisungwook** [comment]
- 오픈소스를 읽는 방법은 2가지가 있다고 생각합니다.
1. 코드를 분석
2. 문서를 보면서 내가 원하는 기능이 있는지 확인

- 내가 주로 오픈소스를 읽었던 것은 2번이었습니다. 문서를 읽을 때는 아키텍처와 장단점을 읽고 quickstart를 읽는 편입니다.
- 하지만, 빠르게 릴리즈 되는 오픈소스는 문서화가 느립니다. 릴리즈 주기가 빠르기 때문입니다. 2024년을 기준으로 backstage가 그 예인 것 같습니다. 릴리즈 주기가 빠른 거는 확실히 문서보다는 코드 분석이 좋습니다. 2024년에 teleport라는 오픈소스 권한을 설정하는 부분이 있었는데, 문서에 표시되지 않는 설정이 있었습니다. @GwonsooLee 은 코드를 보고 바로 설정을 수정했고, 문서에 의존했던 저는 수정을 못했습니다.
