### ISSUE TITLE
시스템엔지니어와 데브옵스엔지니어의 차이

### ISSUE THREAD

**Issue by ymir0804** [GwonsooLee/Podcast#26]
안녕하세요 진행자 선생님들!
첫번째 팟케스트인 데브옵스는 무엇일까?를 듣고 궁금한 사항이 있어 Issue에 등록하려고 합니다!
많은 기업들이 시스템, 데브옵스, SRE엔지니어를 구분하는데 데브옵스와 SRE엔지니어의 차이는 설명해주셨지만, 시스템 엔지니어에 대해서는 설명이 없으셔서 묻고자 Issue 등록합니다!

**Comment by choisungwook** [comment]
@ymir0804 안녕하세요. 질문주신 시스템 엔지니어에 대해 답변 드립니다.

제가 시스템 엔지니어 분을 만나보지 않아서 대답이 부정확한 점 양해 부탁드립니다. 시스템 엔지니어는 말 그대로 "시스템"의 안정적인 운영과 성능 최적화합니다. 주로 `운영체제 또는 cpu, 메모리 등 시스템과 관련된 부분을 집중적`으로 엔지니어링을 합니다. SRE엔지니어가 시스템 신뢰성 향상을 위해 모니터링 등에 집중한다면, 모니터링 결과에서 시스템 부분이 문제가 있다면 시스템 엔지니어가 원인을 밝히고 개선하는 역할을 합니다.

AWS 같은 시스템을 전문으로 하는 회사가 아니면 경험상 기존 엔지니어 또는 개발자가 시스템 엔지니어 역할을 같이 수행하는 것 같습니다. 

chatgpt로 IT엔지니어를 표로 비교했습니다.

![CleanShot 2024-09-23 at 22 14 37@2x](https://github.com/user-attachments/assets/177fad69-0f59-4213-ac9d-7f36af5cba87)

**Comment by ymir0804** [comment]
답변을 달아주셨는데 확인이 늦어 죄송합니다 ㅠㅠ  
비교해주신 표를 확인해보니  데브옵스 엔지니어는 개발자가 개발에 집중하도록 도와주는 포지션이고 시스템 엔지니어는 SRE엔지니어가 관측한 결과를 바탕으로 개선하는 작업하는 엔지니어 인 것으로 이해했는데 정확한지는 잘 모르겠네요....

**Comment by choisungwook** [comment]
> 집중하도록

안녕하세요!. 이해하신게 정확합니다. 
하지만 규모가 작은 회사는 데브옵스/시스템/SRE/인프라 엔지니어를 분류하지 않고 중요도가 높은 업무에 엔지니어를 투입합니다. 위에 정의한 표대로 엔지니어가 일을 하려면 규모가 큰 곳으로 가셔야 합니다.
