### ISSUE TITLE
ssh를 막는게 좋을까?

### ISSUE THREAD

**Issue by choisungwook** [GwonsooLee/Podcast#7]

**Comment by GwonsooLee** [comment]
1. 어드민성 관리를 위해서는 들어가야하는 상황이 생길 수도 있다고 생각합니다. 다만, 누구나 접근해서는 안되고 정말로 필요한 경우에만 권한을 받아서 들어가도록 하는게 좋다고 생각합니다.
2. SSH 자체가 Secure한 쉘이지만, 설정을 잘못하게 되는 경우 Brute Force 공격을 당할 수 있기 때문에 설정에 주의해야 합니다. 예컨대, 포트를 22번으로 사용하지 않고, 다른 포트를 사용하도록 하고, 패스워드 기반이 아니라, Key 기반으로 하는게 좋아보입니다.
3. SSH로 들어가더라도 로깅이 될 수 있도록 접근제어 시스템을 사용하는게 좋을 것 같습니다.

**Comment by choisungwook** [comment]
1. 어드민성 관리를 위해 정말 필요하면 공개키 기반으로 접근을 허용하면 좋다고 생각합니다. 그리고 github처럼 권한을 제한할 수 있으면 최소한의 권한을 제한하고 키만료시간을 짧게 가져가야 합니다.'
2. 그리고 어떤 사람이 무엇을 하는지 추적이 가능해야 합니다.
3. well knwon포트 22번을 사용하지 않는 것이 좋을 것 같습니다.
