### ISSUE TITLE
terraform과 ansible차이는?

### ISSUE THREAD

**Issue by choisungwook** [GwonsooLee/Podcast#8]

**Comment by GwonsooLee** [comment]
테라폼은 인프라나 SaaS 솔루션에서 사용하는 리소스를 코드로 관리하기 위한 도구입니다. 반면 앤서블은 서버 세팅을 immutable하게 진행하기 위한 도구입니다.

**Comment by choisungwook** [comment]
> 블로그: https://malwareanalysis.tistory.com/689

첫 번째 차이는 상태관리 입니다. Ansible은 상태가 없고 Terraform은 상태를 관리합니다. Ansible은 상태를 관리하지 않기 때문에 상태 비교과정이 없습니다. 그러므로 Ansible은 시스템이 이미 코드가 반영되어 있더라도 실행(Ansible 모듈에 따라 실행안할 수 있음)합니다. 반면 Terraform은 상태를 관리하므로 테라폼 코드가 이미 반영되어 있다면 코드를 실행하지 않습니다.

두 번째 차이는 코드 실행구조입니다. Ansible은 ssh프로토콜을 사용하여 코드를 실행하지만 terraform은 provider가 제공하는 API를 사용하여 코드를 실행합니다.
 
세 번째 차이는 사용목적입니다. Anisble은 여러 시스템에 동일한 작업을 할 때 사용합니다. 반면 Terraform은 주로 한 시스템(예: AWS, 솔루션)의 설정 또는 리소스 관리에 사용합니다.
