### ISSUE TITLE
테라폼 디렉터리 관리(서비스 위주, 도메인 위주)

### ISSUE THREAD

**Issue by choisungwook** [GwonsooLee/Podcast#9]
- 서비스 위주 예:

```sh
- ./
-- vpc
-- eks
-- security group
```

- 도메인 위주

``` sh
- ./project_a
-- vpc.tf
-- eks.tf
- ./project_b
-- vpc.tf
-- eks.tf
```

**Comment by GwonsooLee** [comment]
AWS 리소스의 경우에는 주로 AWS 서비스 위주로 생성했습니다. 그 이유는 다음과 같습니다.
1. AWS의 경우, 각 서비스를 레고처럼 조립하는 느낌으로 서비스를 제공합니다. 또한 각 서비스마다 리전 종속적인지, 계정 종속적인지 구분이 다르기 때문에, 각 서비스별로 묶는게 관리하기 편합니다.
2. 도메인에 상관 없이 특정 목적으로 하나의 AWS 서비스만 사용하는 경우도 있어서, 도메인으로 묶는 경우보다 독립적으로 리소스를 생성하기 수월합니다.
3. 도메인과 상관없이 각 AWS 서비스별로 모듈 코드를 별도로 관리하기 편합니다.


다만, 다음과 같은 경우에는 도메인으로 묶는 것이 더 효율적일수도 있을 것 같습니다.
1. 도메인마다 AWS 서비스 사용 방식이 다르거나 관리하는 팀이 다른 경우에는 각 도메인 및 관리자의 성향에 맞게 코드를 분리하는 것도 좋아보입니다.
2. SaaS 솔루션의 경우, 인프라 아키텍쳐를 통째로 복사해야하는 경우가 있는데, 그럴 때는 여러 AWS 서비스를 한번에 생성할 수 있어야 하기 때문에 도메인으로 묶는 것이 좋아보입니다.

**Comment by choisungwook** [comment]
- 직접 경험해 보니 규모가 작으면 서비스 위주로 하는 것이 편하지만, 규모가 커지면 도메인 위주로 하는 것이 좋다고 생각했다.
- 예를 들어 AWS 서비스 별로 프로젝트 구조를 생성하면, 디렉터리 이름만 보고도 어떤 서비스가 있는지 알 수 있다. 하지만, 이 서비스가 어떤 프로젝트에 사용되는지 어렵다. 그 프로젝트가 AWS리소스 10개를 사용한다면 10개 서비스가 여러 디렉터리에 쪼개져 있다.
